export const questionTypes = [
  "FREE_RESPONSE",
  "SELECT_ONE",
  "SELECT_ONE_WRITE_OTHER",
  "SELECT_MULTIPLE",
  "SELECT_MULTIPLE_WRITE_OTHER",
  "DROP_DOWN",
  "SLIDER",
  "LABELED_SLIDER",
  "INSTRUCTIONS",
  "GEO_LOCATION",
  "DATE",
  "TIME",
  "MONTH_AND_YEAR",
  "YEAR",
  "RATING",
  "LIST_OF_TEXT_BOXES",
  "LIST_OF_INTEGER_BOXES",
  "INTEGER",
  "DECIMAL_NUMBER",
  "RANGE",
  "PHONE_NUMBER",
  "ADDRESS",
  "EMAIL_ADDRESS"
];

export const questionTypesWithOptions = [
  "SELECT_ONE",
  "SELECT_MULTIPLE",
  "SELECT_ONE_WRITE_OTHER",
  "SELECT_MULTIPLE_WRITE_OTHER",
  "LIST_OF_TEXT_BOXES",
  "LIST_OF_INTEGER_BOXES",
  "LABELED_SLIDER",
  "DROP_DOWN"
];
